import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { siteUrl, SITEMAP_SEGMENTS, indexableRoutesForSegment } from "@/lib/site";
import { isIndexableHost } from "@/lib/seo";

// Sitemap index per STR-62. References the three segment sitemaps generated by
// app/sitemap.ts via generateSitemaps. Submitted to GSC as the entry point.

function segmentUrl(segment: string): string {
  return `${siteUrl}/sitemap/${segment}.xml`;
}

export async function GET() {
  const host = (await headers()).get("host");
  if (!isIndexableHost(host)) {
    return new NextResponse("Not Found", { status: 404 });
  }

  const lastModified = new Date().toISOString();

  const entries = SITEMAP_SEGMENTS
    .filter((segment) => indexableRoutesForSegment(segment).length > 0)
    .map(
      (segment) =>
        `  <sitemap>\n    <loc>${segmentUrl(segment)}</loc>\n    <lastmod>${lastModified}</lastmod>\n  </sitemap>`,
    )
    .join("\n");

  const body = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</sitemapindex>\n`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
